version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: line-poll-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data:/data/db
    restart: always
    networks:
      - app-network

  mongo-express:
    image: mongo-express:latest
    container_name: line-poll-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    restart: always
    networks:
      - app-network

  line-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: line-poll-bot
    ports:
      - "5000:5000"
    environment:
      - LINE_CHANNEL_ACCESS_TOKEN=${LINE_CHANNEL_ACCESS_TOKEN}
      - LINE_CHANNEL_SECRET=${LINE_CHANNEL_SECRET}
      - GROUP_ID=${GROUP_ID}
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/
      - MONGODB_DB=line_poll_db
      - PORT=5000
    depends_on:
      - mongodb
    restart: always
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge